load your cleaned dataset

In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv(r"C:\Users\Ajvad\Desktop\5th sem ojt\project 1_diabaties\data\processed\project1_diabetes_clean.csv",parse_dates=['last_checkup_date'])

In [43]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0
5,P00755,37,female,0,145.0,80.0,26.0,124.0,22.0,0.488,High,YES,2024-01-10,0
6,P00431,58,male,5,95.0,72.0,26.0,170.0,27.2,0.197,High,NO,2023-12-25,0
7,P00542,58,female,3,150.0,68.0,17.0,124.0,46.0,0.808,Medium,NO,2024-06-20,1
8,P00929,32,female,6,129.0,74.0,26.0,226.0,20.6,0.655,High,UNKNOWN,2023-10-15,1
9,P00513,61,female,0,161.0,77.0,35.0,201.0,35.0,1.229,Medium,YES,2023-12-22,1

In [44]:
df.dtypes

patient_id                      str
age                           int64
gender                          str
pregnancies                   int64
glucose                     float64
blood_pressure              float64
skin_thickness              float64
insulin                     float64
bmi                         float64
diabetes_pedigree           float64
physical_activity               str
smoker                          str
last_checkup_date    datetime64[us]
outcome                       int64
dtype: object

In [45]:
df.shape

(950, 14)

create an age-band feature

In [46]:
df['age_band'] = pd.cut( df['age'], bins=[0, 35, 55, 120] , labels=('Youth','Middle-Aged','Senior'))

In [47]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0,Senior
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,Middle-Aged
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0,Middle-Aged
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1,Senior
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,Senior
5,P00755,37,female,0,145.0,80.0,26.0,124.0,22.0,0.488,High,YES,2024-01-10,0,Middle-Aged
6,P00431,58,male,5,95.0,72.0,26.0,170.0,27.2,0.197,High,NO,2023-12-25,0,Senior
7,P00542,58,female,3,150.0,68.0,17.0,124.0,46.0,0.808,Medium,NO,2024-06-20,1,Senior
8,P00929,32,female,6,129.0,74.0,26.0,226.0,20.6,0.655,High,UNKNOWN,2023-10-15,1,Youth
9,P00513,61,female,0,161.0,77.0,35.0,201.0,35.0,1.229,Medium,YES,2023-12-22,1,Senior

In [48]:
df['age_band'].value_counts()

age_band
Senior         372
Middle-Aged    326
Youth          252
Name: count, dtype: int64

create a BMI category feature

In [49]:
df['bmi_category'] = pd.cut( df['bmi'], bins=[0, 18.5, 25, 30, 120] , labels=('Under-weight ','Normal','Over-weight','Obese'))

In [50]:
df['bmi_category'].value_counts()

bmi_category
Obese            553
Over-weight      235
Normal           124
Under-weight      38
Name: count, dtype: int64

create a glucose band features

In [51]:
df['glucose_band'] = pd.cut( df['glucose'], bins=[0, 100, 126, 300,] , labels=('Normal ','Prediabetic','Diabetic'))

check glucose band distribution

In [52]:
df['glucose_band'].value_counts()

glucose_band
Diabetic       349
Prediabetic    337
Normal         264
Name: count, dtype: int64

create an insulin to glucose ratio feature

In [53]:
df['insulin_glucose'] = df['insulin']/df['glucose']

In [54]:
df.head(10)

,patient_id,age,gender,pregnancies,glucose,blood_pressure,skin_thickness,insulin,bmi,diabetes_pedigree,physical_activity,smoker,last_checkup_date,outcome,age_band,bmi_category,glucose_band,insulin_glucose
0,P00826,79,male,0,124.0,71.0,30.0,124.0,23.4,0.588,Unknown,NO,2023-04-20,0,Senior,Normal,Prediabetic,1.000000
1,P00108,37,male,0,153.0,85.0,24.0,42.0,33.9,0.192,Medium,YES,2024-05-03,1,Middle-Aged,Obese,Diabetic,0.274510
2,P00517,39,female,0,142.0,68.0,22.0,159.0,26.9,0.777,Low,UNKNOWN,2023-07-08,0,Middle-Aged,Over-weight,Diabetic,1.119718
3,P00687,68,female,7,121.0,88.0,26.0,124.0,29.0,1.217,Unknown,YES,2024-04-14,1,Senior,Over-weight,Prediabetic,1.024793
4,P00927,75,female,0,107.0,84.0,31.0,101.0,21.2,0.278,Low,NO,2024-01-27,0,Senior,Normal,Prediabetic,0.943925
5,P00755,37,female,0,145.0,80.0,26.0,124.0,22.0,0.488,High,YES,2024-01-10,0,Middle-Aged,Normal,Diabetic,0.855172
6,P00431,58,male,5,95.0,72.0,26.0,170.0,27.2,0.197,High,NO,2023-12-25,0,Senior,Over-weight,Normal,1.789474
7,P00542,58,female,3,150.0,68.0,17.0,124.0,46.0,0.808,Medium,NO,2024-06-20,1,Senior,Obese,Diabetic,0.826667
8,P00929,32,female,6,129.0,74.0,26.0,226.0,20.6,0.655,High,UNKNOWN,2023-10-15,1,Youth,Normal,Diabetic,1.751938
9,P00513,61,female,0,161.0,77.0,35.0,201.0,35.0,1.229,Medium,YES,2023-12-22,1,Senior,Obese,Diabetic,1.248447

check if there is any imposible value in the ratio

In [55]:
df['insulin_glucose'].describe()

count    950.000000
mean       1.213108
std        1.179183
min        0.054348
25%        0.726708
50%        1.052139
75%        1.512831
max       22.745763
Name: insulin_glucose, dtype: float64

In [56]:
# np.isinf is used check for infinite value 
np.isinf(df['insulin_glucose']).sum()

np.int64(0)

create a pregnencies-per-year-of-age feature

In [57]:
df['pregnancies_rate'] = df['pregnancies']/df['age']

In [58]:
df['pregnancies_rate'].head(10)

0    0.000000
1    0.000000
2    0.000000
3    0.102941
4    0.000000
5    0.000000
6    0.086207
7    0.051724
8    0.187500
9    0.000000
Name: pregnancies_rate, dtype: float64

In [59]:
df['pregnancies_rate'].describe()

count    950.000000
mean       0.042787
std        0.067440
min        0.000000
25%        0.000000
50%        0.000000
75%        0.072661
max        0.380952
Name: pregnancies_rate, dtype: float64

create a days-since lastcheckup date feature

In [60]:
reference_date = df['last_checkup_date'].max()

In [61]:
reference_date

Timestamp('2024-12-28 00:00:00')

In [63]:
df['since_checkup'] = (reference_date - df['last_checkup_date']).dt.days

In [65]:
df['since_checkup'].head(10)

0    618
1    239
2    539
3    258
4    336
5    353
6    369
7    191
8    440
9    372
Name: since_checkup, dtype: int64

create a categorical combination feature

In [66]:
df['activity_smoker'] = df['physical_activity'] + '/' + df['smoker']

In [67]:
df['activity_smoker'].head(10)

0      Unknown/NO
1      Medium/YES
2     Low/UNKNOWN
3     Unknown/YES
4          Low/NO
5        High/YES
6         High/NO
7       Medium/NO
8    High/UNKNOWN
9      Medium/YES
Name: activity_smoker, dtype: str

check thr combination features balance

In [68]:
df['activity_smoker'].value_counts()

activity_smoker
Medium/NO          207
High/NO            195
Low/NO             180
Low/YES             93
Medium/YES          90
High/YES            85
Unknown/NO          36
High/UNKNOWN        22
Unknown/YES         17
Medium/UNKNOWN      12
Low/UNKNOWN          9
Unknown/UNKNOWN      4
Name: count, dtype: int64

list every new inventory column

In [69]:
# activity_smoker = physical + smoker 
# since_checkup = reference - last_checkup_date
# pregnancies_rate = pregnency/age
# insulin_glucose = insulin/glucose
# glucose_band = glucose
# bmi_category = bmi
# age_band = age

In [70]:
df.shape

(950, 21)